import Foundation

// MARK: Support data for creating custom a request

enum LanguagesCodes: String {
    case Arabic = "ar"
    case German = "de"
    case English = "en"
    case Spanish = "es"
    case French = "fr"
    case Hebrew = "he"
    case Italian = "it"
    case Dutch = "nl"
    case Norwegian = "no"
    case Portuguese = "pt"
    case Russian = "ru"
    case Swedish = "sv"
    case Chinese = "zh"
}

enum CountrysCodes: String {
    case UnitedArabEmirates = "ae"
    case Argentina = "ar"
    case Austria = "at"
    case Australia = "au"
    case Belgium = "be"
    case Bulgaria = "bg"
    case Brazil = "br"
    case Canada = "ca"
    case Switzerland = "ch"
    case China = "cn"
    case Colombia = "co"
    case Cuba = "cu"
    case CzechRepublic = "cz"
    case Germany = "de"
    case Egypt = "eg"
    case France = "fr"
    case UnitedKingdom = "gb"
    case Greece = "gr"
    case HongKong = "hk"
    case Hungary = "hu"
    case Indonesia = "id"
    case Ireland = "ie"
    case Israel = "il"
    case India = "in"
    case Italy = "it"
    case Japan = "jp"
    case SouthKorea = "kr"
    case Lithuania = "lt"
    case Latvia = "lv"
    case Morocco = "ma"
    case Mexico = "mx"
    case Malaysia = "my"
    case Nigeria = "ng"
    case Netherlands = "nl"
    case Norway = "no"
    case NewZealand = "nz"
    case Philippines = "ph"
    case Poland = "pl"
    case Portugal = "pt"
    case Romania = "ro"
    case Serbia = "rs"
    case Russia = "ru"
    case SaudiArabia = "sa"
    case Sweden = "se"
    case Singapore = "sg"
    case Slovenia = "si"
    case Slovakia = "sk"
    case Thailand = "th"
    case Turkey = "tr"
    case Taiwan = "tw"
    case Ukraine = "ua"
    case UnitedStates = "us"
    case Venezuela = "ve"
    case SouthAfrica = "za"
}

